---
device: "cuda:0"
env: goto
action_model: "local_policy"
example_path: ../../data/EXAMPLES/goto_1_3_action_space_random.pkl
evaluation_episodes: 1
num_envs: 512
max_timesteps: 15
visualize: False
visualize_traj: True
n_example_frames: 10

embeddings:
  device: "cuda:0"
  type: "t5"
  size: 128
  model: "google-t5/t5-small"
  batch_size: 4096

agent_type: 'diffusion'
model:
use_agent_type: False
sampling_strategy: "ddpm"
num_steps: 64
action_space: 0
num_distractors: 3 
model_type: "edm"
model_store: ../../model_store
ivd_config_path: "./configs/ivd_goto_distractors.yaml"
policy_checkpoint: ""
checkpoint: ""

logging:
  experiment_name: "evaluation_diffusion_agent"
  model_directory: "../../model_store"
  project: DiffusionMultiAgent
  tags: ["BabyAI","DiffusionPlanner","GoToDistractor","Evaluation"]
  mode: online