---
seed: 42
data:
  dataset: babyai
  datapath: ../../data/GOTO_DISTRACTOR/standard_5000_4_3_True_demos/dataset_5000.pkl
  percentage: 0.8
  batch_size: 256
  num_workers: 10

training:
  distributed: True
  early_stopping: False
  max_epochs: 10
  accelerator: "gpu"
  strategy: "ddp_find_unused_parameters_true"
  gpus: [0]

model:
  lr: 0.0001
  action_space: 0
  load:
    load: False

logging:
  experiment_name: "train_ivd_model"
  model_directory: "../../model_store"
  project: ""
  entity: ""
  tags: [""]