---
data:
  dataset: babyai
  path: ../../data/BOSSLEVEL/standard_100000_4_0_False_demos
  filename: dataset_100000.pkl
  percentage: 0.8
  batch_size: 256
  num_workers: 10

training:
  distributed: True
  early_stopping: False
  max_epochs: 100
  accelerator: "gpu"
  strategy: "ddp_find_unused_parameters_true"
  gpus: [0]

model:
  lr: 0.0001
  action_space: 0
  load:
    load: False

logging:
  experiment_name: "ivd_model_all"
  model_directory: "../../model_store"
  project: DiffusionMultiAgent # Wandb project name 
  entity: diffusion-boyz
  tags: ["BabyAI","Diffusion Planner","Sample Efficiency"]