---
0: 
  ivd_model_path: UniversalPoliciesModel/IVD/GOTO_DISTRACTORS_LARGE
  ivd_model_name: ""
  ivd_model_checkpoint: goto_distractors_large_standard.ckpt
1:
  ivd_model_path: UniversalPoliciesModel/IVD/GOTO_DISTRACTORS_LARGE
  ivd_model_name: ""
  ivd_model_checkpoint: goto_distractors_large_no_left.ckpt
2:
  ivd_model_path: UniversalPoliciesModel/IVD/GOTO_DISTRACTORS_LARGE
  ivd_model_name: ""
  ivd_model_checkpoint: goto_distractors_large_no_right.ckpt
3:
  ivd_model_path: UniversalPoliciesModel/IVD/GOTO_DISTRACTORS_LARGE
  ivd_model_name: ""
  ivd_model_checkpoint: goto_distractors_large_diagonal.ckpt
4:
  ivd_model_path: UniversalPoliciesModel/IVD/GOTO_DISTRACTORS_LARGE
  ivd_model_name: ""
  ivd_model_checkpoint: goto_distractors_large_wsad.ckpt
5:
  ivd_model_path: UniversalPoliciesModel/IVD/GOTO_DISTRACTORS_LARGE
  ivd_model_name: ""
  ivd_model_checkpoint: goto_distractors_large_dir8.ckpt
6:
  ivd_model_path: UniversalPoliciesModel/IVD/GOTO_DISTRACTORS_LARGE
  ivd_model_name: ""
  ivd_model_checkpoint: goto_distractors_large_left_right.ckpt
7:
  ivd_model_path: UniversalPoliciesModel/IVD/GOTO_DISTRACTORS_LARGE
  ivd_model_name: ""
  ivd_model_checkpoint: goto_distractors_large_all_diagonal.ckpt