---
device: "cuda:0"
env_name: "BabyAI-GoToObj-v0"
env: goto
action_model: "ivd"
example_path: /scratch-shared/nhoepner/experiments/diffusion_nl2/diffusion_nl/data/GOTO/GOTO_1_full_action_space_random.pkl
evaluation_episodes: 1
num_envs: 512
max_timesteps: 15
visualize: False
visualize_traj: False
n_example_frames: 10
cond_w: 0
embeddings:
  device: "cuda:0"
  type: "t5"
  size: 10
  model: "google-t5/t5-small"
  batch_size: 4096

agent_type: 'diffusion'
model:
model_type: edm
use_agent_type: True
planning_type: "ivd"
sampling_strategy: "ddpm"
num_steps: 64
action_space: 7
num_distractors: 3
model_store: ../../model_store
ivd_model_path: ivd_model_all/DiffusionMultiAgent
ivd_model_name: ajfa75lh
ivd_model_checkpoint: checkpoints/epoch=9-step=11250.ckpt
dm_model_path: ""
dm_model_name: ""
dm_model_checkpoint: ""

logging:
  experiment_name: "evaluation_diffusion_agent"
  model_directory: "../../model_store"
  project: DiffusionMultiAgent # Wandb project name 
  entity: diffusion-boyz
  tags: ["BabyAI","DiffusionPlanner","SampleEfficiency","Evaluation"]