---
device: "cuda:1"
action_model: "ivd"
env: goto
env_name: "BabyAI-GoToObj-v0" 
example_path: /var/scratch/nrhopner/experiments/diffusion_nl/data/GOTO/GOTO_1_full_action_space_random.pkl
evaluation_episodes: 1
num_envs: 512
max_timesteps: 15
visualize: False
n_example_frames: 10
cond_w: 0
embeddings:
  device: "cuda:1"
  type: "t5"
  size: 10
  model: "google-t5/t5-small"
  batch_size: 4096

agent_type: 'diffusion'
model: 
use_agent_type: False
planning_type: "ivd"
sampling_strategy: "ddpm"
num_steps: 64
action_space: 0
num_distractors: 0
model_store: ../../model_store
model_type: "edm"
ivd_model_path: ivd_model_all/DiffusionMultiAgent
ivd_model_name: 023r9dmw
ivd_model_checkpoint: checkpoints/epoch=499-step=9500.ckpt
dm_model_path: "standard_83_edm_1/DiffusionMultiAgent"
dm_model_name: "yj050ke1"
dm_model_checkpoint: "epoch=11111-step=200000.ckpt"
logging:
  experiment_name: "evaluation_diffusion_agent"
  model_directory: "../../model_store"
  project: DiffusionMultiAgent  # Wandb project name 
  entity: diffusion-boyz
  tags: ["BabyAI","DiffusionPlanner","SampleEfficiency","Evaluation"]