---
action_space: 0
data_directory: ../../../data
env: GOTO
fig_directory: ../figures/baby_ai
img_size: 128
max_steps: 25
minimum_length: 4
num_distractors: 0
num_workers: 32
n_episodes: 5000
seed: 42
use_agent_type: True
use_img_obs: False

