---
action_space: 0
data_directory: ../../../data
env: GOTO_DISTRACTOR
fig_directory: ../figures/baby_ai
img_size: 128
max_steps: 25
minimum_length: 4
num_distractors: 3
num_workers: 32
n_episodes: 5000
seed: 42
use_agent_type: True
use_img_obs: False
part: -1
logging:
  mode: disabled
  project: ""
  experiment_name: ""
