---
fig_directory: ../figures/baby_ai
seed: 42
env: GOTO
n_episodes: 5000
num_workers: 32
data_directory: ../../../data
action_space: 0
img_size: 128
use_img_obs: False
max_steps: 25
debug: False
minimum_length: 4
num_distractors: 3
use_agent_type: True
