---
seed: 42
checkpoint: ""
device: "cuda:0"

logging:
  entity: ""
  project: "DiffusionMultiAgent"
  mode: online
  model_directory: "../../model_store"
  experiment_name: "evaluation_imitation_learning"
  tags: ["BabyAI","ImitationLearning","GoToDistractors","Evaluation"]

env: "goto"
encoder_model: "google-t5/t5-small"
num_distractors: 3
action_space: 1
num_envs: 512
evaluation_episodes: 1
max_timesteps: 15