---
goal_type: "obs"
seed: 42

data:
  datapath: "../../data/GOTO_DISTRACTOR/standard_5000_4_3_False_demos/dataset_5000.pkl"
  max_gap: 100
  batch_size: 128
  percentage: 0.8

embeddings:
  device: "cuda:0"
  type: "t5"
  model: "google-t5/t5-small"
  batch_size: 4096

model:
  lr: 0.0001
  large_env: False
  action_space: 0
  use_agent_id: False
  use_unique_agent_heads: False
  load:
    load: False
    checkpoint: ""

training:
  distributed: True
  accelerator: "gpu"
  gpus: [0]
  strategy: "ddp_find_unused_parameters_true"
  max_epochs: 100

logging:
  entity: ""
  project: "DiffusionMultiAgent"
  mode: online
  model_directory: "../../model_store"
  experiment_name: "imitation_learning"
  tags: ["BabyAI","ImitationLearning","GoToDistractors"]

eval:
  eval: True
  device: "cuda:0"
  env: "goto"
  encoder_model: "google-t5/t5-small"
  num_distractors: 3
  action_space: 0
  num_envs: 512
  evaluation_episodes: 1
  max_timesteps: 15